name: Build Matrix (Docker-Image-Config)

on:
  workflow_call:
    outputs:
      matrix:
        description: "Generates the docker-image-config build matrix"
        value: ${{ jobs.matrix_docker_image_config.outputs.matrix }}

jobs:
  matrix_docker_image_config:
    runs-on: "ubuntu-24.04"
    permissions:
      contents: read
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v5

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v5
        with:
          python-version: "3.10"
          poetry-version: "2.3.0"

      - name: Generate matrix
        run: poetry run -- nox -s matrix:docker-image-config

      - id: set-matrix
        run: |
          echo "matrix=$(poetry run -- nox -s matrix:docker-image-config)" >> $GITHUB_OUTPUT

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
