name: Build Matrix (Python and Runners)

on:
  workflow_call:
    outputs:
      matrix:
        description: "Generates the python/runner build matrix"
        value: ${{ jobs.python_runner.outputs.matrix }}

jobs:
  python_runner:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v4

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v4

      - name: Generate matrix
        run: poetry run -- nox -s matrix:python-runner

      - id: set-matrix
        run: |
          echo "matrix=$(poetry run -- nox -s matrix:python-runner)" >> $GITHUB_OUTPUT

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
