name: Slow-Checks

on:
  workflow_call:

jobs:
  build-matrix-python:
    name: Generate Build Matrix for runners
    uses: ./.github/workflows/matrix-python.yml
    permissions:
      contents: read

  build-matrix-runner:
    name: Generate Build Matrix for runners
    uses: ./.github/workflows/matrix-runner.yml
    permissions:
      contents: read

  tests:
    name: Integration-Tests (Python-${{ matrix.python-version }} ${{ matrix.runner }})
    needs:
      - build-matrix-python
      - build-matrix-runner
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJson(needs.build-matrix-python.outputs.matrix).python-version}}
        runner: ${{ fromJson(needs.build-matrix-runner.outputs.matrix) }}

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v6

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v5
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: "2.3.0"

      - name: Run Tests and Collect Coverage
        run: poetry run -- nox -s test:integration -- --coverage

      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: coverage-python${{ matrix.python-version }}-${{matrix.runner}}-slow
          path: .coverage
          include-hidden-files: true
