name: Slow-Checks

on:
  workflow_call:

jobs:
  build-matrix-int-test-config:
    name: Generate Build Matrix for integration tests
    uses: ./.github/workflows/matrix-int-test-config.yml
    permissions:
      contents: read

  tests:
    name: Integration-Tests (Python-${{ matrix.python-version }} Runner-${{ matrix.runner }} TestImgBase-${{matrix.ubuntu-img-int-test}})
    needs:
      - build-matrix-int-test-config
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build-matrix-int-test-config.outputs.matrix) }}

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v6

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v5
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: "2.3.0"

      - name: Run Tests and Collect Coverage
        run: poetry run -- nox -s test:integration -- --coverage --test-image-ubuntu-version ${{matrix.ubuntu-img-int-test}}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: coverage-python${{ matrix.python-version }}-${{matrix.runner}}-slow
          path: .coverage
          include-hidden-files: true
